apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: deploymentwednesday
spec: 
 replicas: 2
 selector: 
  matchLabels: 
   app: my-app 
 template: 
   metadata: 
    labels: 
     app: my-app 
     env: prod 
   spec: 
    containers: 
    - name: my-deployment-container00000
      image: nginx
