apiVersion: v1
kind: Service              # Defines to create Service type Object
metadata:
 name: example-prod
spec:
 type: NodePort
 selector:
   app: my-app             # Apply this service to any pods which has the specific label
   env: prod
 ports:
 - nodePort: 32410           # Containers port exposed
   protocol: TCP
   port: 80
   targetPort: 80           # Pods port
Footer
